# Site settings
title: Christiana Kroondyk
email: christianakroondyk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Melt Ice Cream makes handmade quality ice cream.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meltnorthshore.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

timezone: US/Eastern
